development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: psk_api_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: psk_api_production
